language: python

python:
  - 2.7
  - 3.6

before_install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  - python setup.py check --strict

script:
  - make test

after_success:
  - coveralls

deploy:
  provider: script
  script: bash etc/pythonanywhere/reload.sh
  on:
    branch: master
    python: 3.6
